---
version: '3.7'

services:

    es:
        container_name: tla-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            discovery.type: single-node
        ports:
            - ${ES_PORT:-9150}:9150
        stdin_open: true
        tty: true
        restart: unless-stopped

    populate:
        container_name: tla-ingest
        depends_on:
            - es
        build:
            context: .
        environment:
            - ES_HOST=es
            - ES_PORT=9150
            - SAMPLE_URL = https://sandbox.zenodo.org/record/715217/files/tla-data.tar.gz
        tty: true
        command: "ingest"

    backend:
        container_name: tla-backend
        depends_on:
            - populate
        build:
            context: .
        environment:
            - ES_HOST=es
            - ES_PORT=9150
        ports:
            - 9000:9000
        tty: true
        restart: unless-stopped

...
