---

logging:
    file:
        name: app.log

server:
    port: 9000
    error:
        whitelabel:
            enabled: false

tla:
    es:
        port: ${ES_PORT:9201}
        host: ${ES_HOST:localhost}
